version: 2.1
workflows:
  version: 2
  deploy:
      jobs:
      - pantheon/push
      - playground/npmbuild_and_persist:
          package_lock_location: "embed-files-in-node-server"
          path_to_persist: "embed-files-in-node-server/build"
          build_command: "npm run build-for-gcp"
          requires:
            - pantheon/push
          pre-steps:
            - playground/setbashenv
            - run:
                name: set up embed
                command: |
                  git clone git@github.com:stevector/embed-files-in-node-server.git
                  cd embed-files-in-node-server
                  rm -r frontity
                  cd ..
                  mv frontity embed-files-in-node-server/frontity
                  cd embed-files-in-node-server/frontity
                  npm ci
                  cd ..
                  npm ci


      - deploy_cloud_function:
          requires:
            - playground/npmbuild_and_persist


jobs:
  deploy_cloud_function:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - playground/setbashenv
      - run: ls -al
      - run: cd embed-files-in-node-server/build && ls -al
      - run:
          name: Login to gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: deploy
          # @todo make a variable for serverlessplayground and runtime, and probably everything in gcloud functions deploy.
          command: |
            gcloud functions deploy ${TERMINUS_SITE}--${TERMINUS_ENV} --project=serverlessplayground --runtime=nodejs10 --trigger-http  --allow-unauthenticated  --entry-point=default --source=embed-files-in-node-server/build --set-env-vars="TERMINUS_SITE=${TERMINUS_SITE},TERMINUS_ENV=${TERMINUS_ENV}"

orbs:
  pantheon: pantheon-systems/pantheon@0.2.0
  playground: fauxalgore/playground@0.0.2
